# Generated by Django 6.1.1 on 2026-09-28 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_amistad_de_usuario_alter_amistad_para_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amistad',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='like',
            name='fecha',
        ),
        migrations.AddField(
            model_name='mensajeprivado',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='mensajeprivado',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajeprivado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mensajes/'),
        ),
        migrations.AlterField(
            model_name='amistad',
            name='de_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amistad',
            name='para_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeprivado',
            name='contenido',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mensajeprivado',
            name='de_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeprivado',
            name='para_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Guardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
        migrations.CreateModel(
            name='HistoriaDestacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='historias/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('privado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Compartido',
        ),
    ]
